### ISSUE TITLE
Mock endpoints based on API specs from standards such as RAML and Swagger

### ISSUE THREAD

**Issue by kylehayes** [devlucky/Kakapo.js#126]
It seems mocks like this should be generated based on an agreed up specification of the REST API or at least have the option to. RAML and Swagger are the two most popular standards for this. It would be nice to not have to code the mock itself but just define the API once in a spec file and let this figure out the rest.

**Comment by zzarcon** [comment]
Hi @kylehayes so if I understood properly, what you want to achieve is reusing the `.yml` you have created for RAML and avoid to replicate that logic in Kakapo right? Can you provide an example of how you will like to use it? maybe this...?

```javascript
import {Database} from 'kakapo';

const db = new Database({schema: 'raml'})
const userDefinition = require('user.raml')

db.register('user', userDefinition)
```

Please correct me if I'm wrong since I don't experience with those standards but I'd like to implement them if are useful :)

**Comment by zzarcon** [comment]
@kylehayes ping
